services:
  floc:
    container_name: floc
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '5173:5173'
    command: ['/bin/sh', '-c', 'npm install && npm run dev']

  pocketbase:
    container_name: pocketbase
    image: alpine:latest
    working_dir: /pocketbase
    volumes:
      - ./.pocketbase/:/pocketbase
    command: ['./pocketbase', 'serve', '--http=0.0.0.0:8090']
    ports:
      - '8090:8090'

  grafana:
    image: grafana/grafana:11.6.1
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - floc

  loki:
    image: grafana/loki:3.5.0
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    networks:
      - floc

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./.grafana/config.alloy:/etc/alloy/config.alloy
      - ./.grafana/logs:/var/log:ro
    command: ['--config.file=/etc/alloy/config.alloy']
    depends_on:
      - loki
    networks:
      - floc

volumes:
  grafana-storage:

networks:
  floc:
