services:
  floc:
    container_name: floc
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '4173:4173'
    command: ['/bin/sh', '-c', 'npm install && npm run prod']
    networks:
      - floc

  pocketbase:
    container_name: pocketbase
    image: alpine:latest
    working_dir: /pocketbase
    volumes:
      - ./.pocketbase/:/pocketbase
    command: ['./pocketbase', 'serve', '--http=0.0.0.0:8090']
    ports:
      - '8090:8090'
    networks:
      - floc

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./.grafana/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    environment:
      - GF_PATHS_PROVISIONING=${GF_PATHS_PROVISIONING}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_FEATURE_TOGGLES_ENABLE=${GF_FEATURE_TOGGLES_ENABLE}
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
    depends_on:
      - loki
    networks:
      - floc

  loki:
    container_name: loki
    image: grafana/loki:3.5.0
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./.grafana/loki/config.yaml:/etc/loki/config.yaml
    networks:
      - floc

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./.grafana/log:/var/log
      - ./.grafana/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - floc

networks:
  floc:
