export enum EInvoiceType {
	QUOTE = 'QUOTE',
	INVOICE = 'INVOICE',
	CREDIT_NOTE = 'CREDIT_NOTE',
	DEBIT_NOTE = 'DEBIT_NOTE',
	RECEIPT = 'RECEIPT',
	PROFORMA = 'PROFORMA',
	PURCHASE_ORDER = 'PURCHASE_ORDER',
	OTHER = 'OTHER'
}
